version: "3"

services:
  nginx:
    build:
      context: .
    ports:
      - "8000:80"
      - "9000:443"
    volumes:
      - ./dist:/app/dist
      - ./certbot/test:/var/www/certbot/:ro

  certbot:
    volumes:
      - ./certbot/test:/var/www/certbot/:rw
