# name: Test
# on:
#   pull_request:
#   push: 
#     branches: 
#       - main 
#       - feature/server
#       - feature/client
# 
# jobs:
#   test:
#     name: Run test suite
#     runs-on: ubuntu-latest
#     env:
#       COMPOSE_FILE: ./compose.test.yaml
#       DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
#       DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
# 
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
# 
#     - name: Login to DockerHub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKERHUB_USER }}
#         password: ${{ secrets.DOCKERHUB_PASSWORD }}
# 
#     - name: Build docker images
#       run: docker-compose -f compose.test.yaml build
# 
#     - name: Run tests
#       run: docker-compose -f compose.test.yaml run --rm test sh -c "npm run test"
